# Reference: https://github.com/actions/labeler/blob/master/README.md
  
# Add 'linx-commerce' label to any change within the 'linx-commerce' app
linx-commerce:
  - apps/linx-commerce*/**/*

# Add 'pagarme' label to any change within the 'pagar-me' app
pagarme:
  - apps/pagar-me*/**/*

# Add 'megaerp' label to any change within the 'megaerp' app
megaerp:
    - apps/megaerp*/**/*

# Add 'bling' label to any change within the 'bling' app
bling:
    - apps/bling*/**/*